# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = with config.boot.kernelPackages; [
  ];
  boot.extraModprobeConfig = ''
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ee637313-ce0e-420a-82d0-9464a9ba2963";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/3B9D-ED4E";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/mnt/ext-hdd" = {
    device = "/dev/disk/by-label/Backup";
    fsType = "ext4";
    options = ["auto" "nofail" "user"];
  };

  environment.etc."crypttab".text = ''
    private_stash /dev/disk/by-uuid/89c1c461-917f-477d-b504-378357e3b07e none noauto
  '';

  fileSystems."/mnt/private" = {
    device = "/dev/mapper/private_stash";
    fsType = "ext4";
    options = ["noauto"];
  };

  swapDevices = [];
  zramSwap.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; # needed for flakes
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.opentabletdriver.enable = true;
}
